# Generated by devtools/yamaker (pypi).

PY3_LIBRARY()

SUBSCRIBER(g:python-contrib)

VERSION(0.21.1)

LICENSE(MIT)

PEERDIR(
    contrib/python/click
    contrib/python/rich
    contrib/python/shellingham
    contrib/python/typer-slim
    contrib/python/typing-extensions
)

NO_LINT()

RESOURCE_FILES(
    PREFIX contrib/python/typer/
    .dist-info/METADATA
    .dist-info/entry_points.txt
    .dist-info/top_level.txt
)

END()
